package com.internflow.backend.service;
import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.internflow.backend.entity.*; import com.internflow.backend.entity.enums.*; import com.internflow.backend.exception.ApiException; import com.internflow.backend.repository.*; import com.internflow.backend.security.UserPrincipal;
@Service public class CoSupervisorService { private final CoSupervisorAssignmentRepository assignments; private final InternshipRepository internships; private final UserRepository users; private final NotificationService notifications;
 public CoSupervisorService(CoSupervisorAssignmentRepository a,InternshipRepository i,UserRepository u,NotificationService n){assignments=a;internships=i;users=u;notifications=n;}
 @Transactional public void invite(Long internshipId,Long supervisorId,UserPrincipal p){ Internship in=internships.findById(internshipId).orElseThrow(()->ApiException.notFound("Internship not found")); if(!in.getSupervisor().getId().equals(p.getId()))throw ApiException.forbidden("Only the primary supervisor may invite a co-supervisor"); User s=users.findById(supervisorId).orElseThrow(()->ApiException.notFound("Supervisor not found")); if(s.getRole()!=UserRole.supervisor)throw ApiException.badRequest("User is not a supervisor"); if(s.getId().equals(p.getId()))throw ApiException.badRequest("Primary supervisor cannot invite themselves"); CoSupervisorAssignment a=assignments.findByInternshipIdAndSupervisorId(internshipId,supervisorId).orElseGet(CoSupervisorAssignment::new); a.setInternship(in);a.setSupervisor(s);a.setStatus("pending");assignments.save(a);notifications.send(s.getId(),NotificationType.system,"Co-supervision invitation", "You were invited to co-supervise "+in.getIntern().getName()+". Accepting grants read-only access. [internship:"+in.getId()+"]"); }
 @Transactional public void respond(Long internshipId,boolean accept,UserPrincipal p){ CoSupervisorAssignment a=assignments.findByInternshipIdAndSupervisorId(internshipId,p.getId()).orElseThrow(()->ApiException.notFound("Invitation not found"));a.setStatus(accept?"accepted":"declined");assignments.save(a);notifications.send(a.getInternship().getSupervisor().getId(),NotificationType.system,"Co-supervision invitation updated",a.getSupervisor().getName()+(accept?" accepted":" declined")+" the invitation."); }
 @Transactional public void remove(Long internshipId,Long supervisorId,UserPrincipal p){ Internship in=internships.findById(internshipId).orElseThrow(()->ApiException.notFound("Internship not found"));if(!in.getSupervisor().getId().equals(p.getId()))throw ApiException.forbidden("Only the primary supervisor may remove a co-supervisor");assignments.findByInternshipIdAndSupervisorId(internshipId,supervisorId).ifPresent(assignments::delete); }
}
